# Generated by Django 2.1.4 on 2018-12-12 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oingo', '0002_auto_20181211_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='repetition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='tname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='oingo.Tag'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
