# Generated by Django 2.1.4 on 2018-12-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oingo', '0004_auto_20181212_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_request',
            field=models.BooleanField(default=True),
        ),
    ]
