# Generated by Django 2.1.4 on 2018-12-13 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oingo', '0006_auto_20181213_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friends',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friends',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_friend', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
