# Generated by Django 2.1.4 on 2018-12-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oingo', '0008_auto_20181213_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='friends',
            new_name='friend',
        ),
    ]
