# Generated by Django 2.1.4 on 2018-12-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oingo', '0009_auto_20181213_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
