# Generated by Django 2.1.4 on 2018-12-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oingo', '0010_userprofile_last_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
