# Generated by Django 2.1.4 on 2018-12-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oingo', '0011_auto_20181214_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='lname',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filter',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
