# Generated by Django 2.1.4 on 2018-12-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oingo', '0012_auto_20181214_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='fname',
            field=models.CharField(default='aaa', max_length=50),
            preserve_default=False,
        ),
    ]
