# Generated by Django 2.1.4 on 2018-12-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oingo', '0013_filter_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_lon',
            field=models.FloatField(default=0),
        ),
    ]
